GET http://localhost:3001/api/blogs

###

GET http://localhost:3001/api/users

###

POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "username43",
  "name": "root2",
  "password": "admin"
}

###

POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3RVc2VyIiwiaWQiOiI2MWU1NzE1MmQ0YWE5Y2E4N2E4MGRiZDUiLCJpYXQiOjE2NDI0NTg0MTksImV4cCI6MTY0MjQ2MjAxOX0.GDdTJA1siqr0osqMObjrNusKh7ymRo6C0N2QALGGLok

{
  "title": "hellothere",
  "url": "randomurl",
  "author": "yes"
}

###

GET http://localhost:3001/api/blogs/WRONGID

###

DELETE http://localhost:3001/api/blogs/61e5822f2cbdfc1d1a486f71
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3RVc2VyIiwiaWQiOiI2MWU1NzE1MmQ0YWE5Y2E4N2E4MGRiZDUiLCJpYXQiOjE2NDI0MzA5ODl9.lW2Qv6P1slfXPUWRwlgqM7qbHJLYgean502IQ5hadVg

###

POST http://localhost:3001/api/login
Content-Type: application/json

{
  "username": "rootUser",
  "password": "admin"
}
 
