GET http://localhost:3001/api/blogs

###

GET http://localhost:3001/api/users

###

POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "username43",
  "name": "root2",
  "password": "admin"
}

###

POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3RVc2VyIiwiaWQiOiI2MWU1NzE1MmQ0YWE5Y2E4N2E4MGRiZDUiLCJpYXQiOjE2NDI0MzIzNzYsImV4cCI6MTY0MjQzNTk3Nn0._I78ace199sV5QcsigaOrty14GLJsgMAL4AhNobGMJA

{
  "title": "NEWTESTdddd",
  "url": "hello.com2256",
  "author": "authorname22456"
}

###

GET http://localhost:3001/api/blogs/WRONGID

###

DELETE http://localhost:3001/api/blogs/61e5822f2cbdfc1d1a486f71
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3RVc2VyIiwiaWQiOiI2MWU1NzE1MmQ0YWE5Y2E4N2E4MGRiZDUiLCJpYXQiOjE2NDI0MzA5ODl9.lW2Qv6P1slfXPUWRwlgqM7qbHJLYgean502IQ5hadVg

###

POST http://localhost:3001/api/login
Content-Type: application/json

{
  "username": "rootUser",
  "password": "admin"
}
 
